# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(996, 794)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setSpacing(10)
        self.verticalLayout.setObjectName("verticalLayout")
        self.picturePreview = QtWidgets.QGraphicsView(self.centralwidget)
        self.picturePreview.setMinimumSize(QtCore.QSize(100, 100))
        self.picturePreview.setObjectName("picturePreview")
        self.verticalLayout.addWidget(self.picturePreview)
        self.watermarkPreview = QtWidgets.QGraphicsView(self.centralwidget)
        self.watermarkPreview.setObjectName("watermarkPreview")
        self.verticalLayout.addWidget(self.watermarkPreview)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, 0, 0, -1)
        self.horizontalLayout.setSpacing(3)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.selectPicture = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.selectPicture.sizePolicy().hasHeightForWidth())
        self.selectPicture.setSizePolicy(sizePolicy)
        self.selectPicture.setMinimumSize(QtCore.QSize(100, 10))
        self.selectPicture.setObjectName("selectPicture")
        self.horizontalLayout.addWidget(self.selectPicture)
        self.selectWatermark = QtWidgets.QPushButton(self.centralwidget)
        self.selectWatermark.setObjectName("selectWatermark")
        self.horizontalLayout.addWidget(self.selectWatermark)
        self.watermark = QtWidgets.QPushButton(self.centralwidget)
        self.watermark.setObjectName("watermark")
        self.horizontalLayout.addWidget(self.watermark)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 1)
        self.horizontalLayout.setStretch(2, 1)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout.setStretch(0, 6)
        self.verticalLayout.setStretch(1, 3)
        self.verticalLayout.setStretch(2, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 996, 30))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        self.selectPicture.clicked.connect(MainWindow.onSelectPictureClicked)
        self.watermark.clicked.connect(MainWindow.onWatermarkClicked)
        self.selectWatermark.clicked.connect(MainWindow.onSelectWatermarkClicked)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.selectPicture.setText(_translate("MainWindow", "Select Picture"))
        self.selectWatermark.setText(_translate("MainWindow", "Select Watermark"))
        self.watermark.setText(_translate("MainWindow", "Watermark the Picture"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
